dist: trusty

os:
- linux

language: go

go:
- 1.7
- 1.8
- tip

before_install:
- go get github.com/Masterminds/glide
- go get github.com/mattn/goveralls

install:
- glide install

script:
- goveralls -service=travis-ci

after_success:
- test -n "$TRAVIS_TAG" && curl -sL https://git.io/goreleaser | bash
