apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: chaoskube
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: chaoskube
    spec:
      containers:
      - name: chaoskube
        image: docker.io/linki/chaoskube:latest
        imagePullPolicy: Always
      - name: kubectl
        image: quay.io/coreos/hyperkube:v1.4.5_coreos.0
        command:
        - /hyperkube
        args:
        - kubectl
        - proxy
