apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: chaoskube
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: chaoskube
    spec:
      containers:
      - name: chaoskube
        image: docker.io/linki/chaoskube:latest
        args:
        - --in-cluster
        - --interval=10m
        imagePullPolicy: Always
