apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: chaoskube
  labels:
    app: chaoskube
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: chaoskube
    spec:
      containers:
      - name: chaoskube
        image: quay.io/linki/chaoskube:v0.2.2
        args:
        - --in-cluster
        - --interval=10m
