[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "~1.0.3"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "~1.2.1"

[[constraint]]
  name = "gopkg.in/alecthomas/kingpin.v2"
  version = "~2.2.5"

[[constraint]]
  branch = "release-1.10"
  name = "k8s.io/api"

[[constraint]]
  branch = "release-1.10"
  name = "k8s.io/apimachinery"

[[constraint]]
  name = "k8s.io/client-go"
  version = "~7.0.0"

[[constraint]]
  name = "github.com/prometheus/client_golang"
  revision = "3653aff4d509dd87a6ba41b82d57c0c662733e14"

[[override]]
  name = "github.com/golang/protobuf"
  version = "1.1.0"
