[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "~1.0.3"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "~1.2.1"

[[constraint]]
  name = "gopkg.in/alecthomas/kingpin.v2"
  version = "~2.2.5"

[[constraint]]
  branch = "release-1.10"
  name = "k8s.io/api"

[[constraint]]
  branch = "release-1.10"
  name = "k8s.io/apimachinery"

[[constraint]]
  name = "k8s.io/client-go"
  version = "~7.0.0"

[[constraint]]
  name = "github.com/prometheus/client_golang"
  version = "0.8.0"

[[override]]
  name = "github.com/golang/glog"
  source = "github.com/kubermatic/glog-logrus"

[[override]]
  name = "github.com/golang/protobuf"
  version = "1.1.0"
