[[constraint]]
  name = "github.com/alecthomas/kingpin"
  version = "~2.2.6"

[[constraint]]
  name = "github.com/prometheus/client_golang"
  version = "~0.9.0"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "~1.1.1"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "~1.2.2"

[[constraint]]
  branch = "release-1.12"
  name = "k8s.io/api"

[[constraint]]
  branch = "release-1.12"
  name = "k8s.io/apimachinery"

[[constraint]]
  name = "k8s.io/client-go"
  version = "~9.0.0"

[[override]]
  name = "github.com/Azure/go-autorest"
  version = "~10.15.5"

[prune]
  go-tests = true
  unused-packages = true
