[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "~1.0.3"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "~1.2.1"

[[constraint]]
  name = "gopkg.in/alecthomas/kingpin.v2"
  version = "~2.2.5"

[[constraint]]
  name = "k8s.io/client-go"
  version = "~4.0.0"
