apiVersion: apps/v1
kind: Deployment
metadata:
  name: chaoskube
  labels:
    app: chaoskube
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: chaoskube
  template:
    metadata:
      labels:
        app: chaoskube
    spec:
      serviceAccountName: chaoskube
      containers:
      - name: chaoskube
        image: chaoskube:single-namespace-enabled-2
        args:
        # kill a pod every 10 minutes
        - --interval=1m
        # exclude all pods in the kube-system namespace
        - --namespaces=foo,kube-system
        # terminate pods for real: this disables dry-run mode which is on by default
        - --no-dry-run
        - --debug
        securityContext: {}
          # runAsNonRoot: true
          # runAsUser: 65534
          # readOnlyRootFilesystem: true
          # capabilities:
          #   drop: ["ALL"]

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: chaoskube
  labels:
    app: chaoskube
